package fr.inria.rsommerard.wifidirect.core.widi

object Intent {

  val WIFI_P2P_PEERS_CHANGED_ACTION: String = "mock.PEERS_CHANGED"
  val WIFI_P2P_STATE_CHANGED_ACTION: String = "mock.STATE_CHANGED"
  val WIFI_P2P_CONNECTION_CHANGED_ACTION: String = "mock.CONNECTION_STATE_CHANGE"
  val WIFI_P2P_THIS_DEVICE_CHANGED_ACTION: String = "mock.THIS_DEVICE_CHANGED"
  val WIFI_P2P_THIS_DEVICE_CHANGED_ACTION_EMULATOR: String = "mock.THIS_DEVICE_CHANGED_EMULATOR"

  val CONNECT: String = "mock.CONNECT"
}
